### ISSUE TITLE
cannot ignore directory

### ISSUE THREAD

**Issue by dreaming121** [cckuailong/py2sec#1]
when I use -m [directory/] to maintain a directory, it will appear error -- "dir_list is a list cannot be split". I go to see the source code. there are some problems.
1. in line 76 and 77 temp[0],temp[1:-1] will cut off the last one and file just can be chosen the first one.
My suggestion is change the rule, right the directory first then file like [a/,b/],file1,file2. Then use temp[0] to take directory, temp[1:] to take file_list
2. in line 87, dir_list is a list so cannot use .split 

It is wonderful to transform project and maintain file. But maintain directory still have some issues those issue also in your last project "py2o". Thank you!

**Comment by cckuailong** [comment]
Oh! Your advice is really nice. I got a mistake on "-m" option. I have fixed the bug seconds ago. Thank you for point out the bug.
