### ISSUE TITLE
加密完成后无法正常运行

### ISSUE THREAD

**Issue by liunnnnn** [cckuailong/py2sec#13]
按照流程进行加密后,提示加密成功.
![image](https://user-images.githubusercontent.com/41818637/92430713-28e3ea80-f1c8-11ea-9ea3-afe58842f87f.png)

但是执行加密后的文件的时候报错:
![image](https://user-images.githubusercontent.com/41818637/92430864-92fc8f80-f1c8-11ea-90cd-1cf4d7a682e9.png)

**Comment by cckuailong** [comment]
python3 rsa.py运行会报错吗

**Comment by liunnnnn** [comment]
> python3 rsa.py运行会报错吗

不会, 就是一个很简单的脚本

**Comment by cckuailong** [comment]
> > python3 rsa.py运行会报错吗
> 
> 不会, 就是一个很简单的脚本

你的python命令是py2的吗，可能需要python3命令去执行

**Comment by liunnnnn** [comment]
> > > python3 rsa.py运行会报错吗
> > 
> > 
> > 不会, 就是一个很简单的脚本
> 
> 你的python命令是py2的吗，可能需要python3命令去执行

我的命令是py3的, 那是我开启的一个py3的虚拟环境, 所以输入python就会默认调用pyhton3解释器

**Comment by liunnnnn** [comment]
> > > python3 rsa.py运行会报错吗
> > 
> > 
> > 不会, 就是一个很简单的脚本
> 
> 你的python命令是py2的吗，可能需要python3命令去执行

你那边测试没问题吗?

**Comment by cckuailong** [comment]
so文件属于动态链接库，需要其他python文件中 from rsa import *，这样去导入和使用

**Comment by liunnnnn** [comment]
> so文件属于动态链接库，需要其他python文件中 from rsa import *，这样去导入和使用

好的我已经解决了问题 谢谢解答

**Comment by liunnnnn** [comment]
已解决
