### ISSUE TITLE
cleanup

### ISSUE THREAD

**Issue by edwardsun** [cckuailong/py2sec#4]
Hi,

Could you please add clean-ups for package builds? Ideally after package building there will only be a "result/package" directory. There can be a flag to retain intermediate steps for debugging purpose if user is interested.

Thanks.

**Comment by cckuailong** [comment]
Thx for the suggestion, I add the --release flag to clean up the temp files

**Comment by edwardsun** [comment]
Hi. I've just tested the -r parameter. It does not seem to work. In fact, there were only cythonization but no compilation or linking. Could you please take a look?

**Comment by cckuailong** [comment]
Sorry, I do not understand your advice. My understanding is you do not want the intermediate files.
So, you want to reduce the screen output details?

**Comment by edwardsun** [comment]
I did not mean verbosity. 
![image](https://user-images.githubusercontent.com/359830/80604295-8dfc2800-89ff-11ea-9e89-3319f740c32d.png)
![image](https://user-images.githubusercontent.com/359830/80604336-98b6bd00-89ff-11ea-90a5-cff98a1e5516.png)
If you take a look at the screen shots, no .so files were actually generated if '-r' parameter was used. I guess this is a bug?
The intended behavior is to generate all .so files and then clean up temporary files, right?

**Comment by cckuailong** [comment]
Thank you for it.
I delete the temp files at the end of the project
`if opts.release:
        clearTmpFiles()
`
I tested the `python3 py2sec.py -d example -p 3 -r`, and I got the right .so files.
Maybe you can try to download the newest version of py2sec.

**Comment by edwardsun** [comment]
Hi,

Here is the output log.
yyang@futures-server:~/Dropbox/curves$ **python3 py2sec.py -d curve -p 3 -r**
> pyEncrypt
python3 tmp_py2sec_build.py build_ext
Compiling curve/examples/regular_engines.py because it changed.
Compiling curve/construction/solver.py because it changed.
Compiling curve/convention/holiday.py because it changed.
Compiling curve/construction/__init__.py because it changed.
Compiling curve/construction/engine.py because it changed.
Compiling curve/__init__.py because it changed.
Compiling curve/convention/cashflow.py because it changed.
Compiling curve/construction/constraint.py because it changed.
Compiling curve/examples/__init__.py because it changed.
Compiling curve/convention/businessday.py because it changed.
Compiling curve/examples/json_engines.py because it changed.
Compiling curve/convention/__init__.py because it changed.
Compiling curve/convention/daycount.py because it changed.
Compiling curve/construction/objective.py because it changed.
Compiling curve/utils.py because it changed.
Compiling curve/translation.py because it changed.
Compiling curve/convention/frequency.py because it changed.
[ 1/17] Cythonizing curve/__init__.py
[ 2/17] Cythonizing curve/construction/__init__.py
[ 3/17] Cythonizing curve/construction/constraint.py
[ 4/17] Cythonizing curve/construction/engine.py
[ 5/17] Cythonizing curve/construction/objective.py
[ 6/17] Cythonizing curve/construction/solver.py
[ 7/17] Cythonizing curve/convention/__init__.py
[ 8/17] Cythonizing curve/convention/businessday.py
[ 9/17] Cythonizing curve/convention/cashflow.py
[10/17] Cythonizing curve/convention/daycount.py
[11/17] Cythonizing curve/convention/frequency.py
[12/17] Cythonizing curve/convention/holiday.py
[13/17] Cythonizing curve/examples/__init__.py
[14/17] Cythonizing curve/examples/json_engines.py
[15/17] Cythonizing curve/examples/regular_engines.py
[16/17] Cythonizing curve/translation.py
[17/17] Cythonizing curve/utils.py

Py2Sec Encrypt Finished

yyang@futures-server:~/Dropbox/curves$ ls result/
yyang@futures-server:~/Dropbox/curves$

I do not think any .so file has been generated as the result directory is empty.
I'm already using the latest version.
Could you please take a look again?

**Comment by edwardsun** [comment]
Well if I remove the '-r' the program still does not generate .so file. But the old version was able to build .so files. Maybe this can give you more clues.

**Comment by cckuailong** [comment]
Hi, thank you for that. Maybe you can put the content of tmp_py2sec_build.py here.
What's more, you can run "python3 tmp_py2sec_build.py build_ext" and put the error messages here.
I'll find the bugs. Thank you very much.

**Comment by edwardsun** [comment]
Here is the content of tmp_py2sec_build.py
![image](https://user-images.githubusercontent.com/359830/80660410-9aad6a00-8a59-11ea-90fc-6af685a83334.png)

I also ran the **python3 tmp_py2sec_build.py build_ext** and did find an error in my .py code.

![image](https://user-images.githubusercontent.com/359830/80660466-c6c8eb00-8a59-11ea-8619-43a89aa8a429.png)

That said, would it be possible for you to catch the error and emit some message?

Thanks.

**Comment by cckuailong** [comment]
It's able to catch the error now. Thx :)

**Comment by edwardsun** [comment]
Many thanks. I've not verified it but will close the ticket for now.
