### ISSUE TITLE
one single .so?

### ISSUE THREAD

**Issue by edwardsun** [cckuailong/py2sec#5]
Hi,

This is definitely a great tool. Is it possible to package everything into one dynamic library file ".so"? Currently a package contains quite a few ".so"s.

Thanks.

**Comment by cckuailong** [comment]
Hi, 
Maybe you need the pyinstaller to do this, or use gcc to combine the .a files into one .so

**Comment by edwardsun** [comment]
No worries if this feature is not in your development plan. Just out of curiosity. Thanks again for the tool.
